title: To Do List App | whdzera
username: whdzera
email: whdzera@gmail.com
baseurl: "/to-do-list-app"
url: "" 
twitter_username: whdzera
github_username:  rokhimin/to-do-list-app
donate_username: whdzera
